### ISSUE TITLE
js error with clean hexya-demo.

### ISSUE THREAD

**Issue by leopku** [hexya-addons/web#8]
1. follow [installation guide](http://hexya.io/docs/install/)
2. browsing `localhost:8080`
3. login
4. url auto jumped to `http://localhost:8080/web/#cids=1` and error occurred

```
Error:


Traceback:
TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at computeFloatOuterWidthWithMargins (http://localhost:8080/static/web/src/js/core/dom.js:551:27)
    at _adapt (http://localhost:8080/static/web/src/js/core/dom.js:540:35)
    at Object.initAutoMoreMenu (http://localhost:8080/static/web/src/js/core/dom.js:474:9)
    at http://localhost:8080/static/web/src/js/chrome/menu.js:72:17
    at async Promise.all (index 2)
    at async Promise.all (index 0)
```

**Comment by jay009id** [comment]
Check the log in terminal. Did you install saas as well as `less` : `npm install -g less saas`
